version: "3.3"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=vanhackathon
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root

  api:
    image: skipthedishes/vanhackathon
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=vanhackathon
      - DATABASE_PORT=3306
    command: bash -c "sleep 10;"
