version: "3.1"

services:
  db:
      image: mysql
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=vanhackathon
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
